### ISSUE TITLE
Test hw1 CI

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/nsdhw_20sp#7]
@tigercosmos could you test if CI is working?  PR #4 ran into a bug that I tried to fix with #5, but to fully validate my fix another GitHub account is needed.

You may follow what I did in #6 for the test.

**Comment by yanagiragi** [comment]
@yungyuc After several tests, I believe the workflow should change to [this](https://github.com/yanagiragi/nsdhw_20sp/blob/hw1/.github/workflows/hw1.yml) (probably need to get rid of some echos). FYI, the difference can be found in [here](https://github.com/yanagiragi/nsdhw_20sp/commit/0a983a3ec131ce3a2ef712bbacd76c56803031cf).

Please correct me if I am wrong, it seems the fix of #5 tries to fill the ```$username``` with the first split part of ```$GITHUB_REF```. However if PR is sent from a forked project, ```$GITHUB_REF``` become ```refs/pull/4/merge``` while 4 stands for the id of the PR.

According to the [doc](https://developer.github.com/v3/pulls/#link-relations), when the PR is sent from a forked project, I use ```${{ github.event.pull_request.head.user.login }}``` to get the id of the user who submit the PR. In other cases, which means the PR is sent from the owner of the repo, the way to get ```$username``` is fall back to #5 .

Through it is against the hand in principle, I made a quick test [here](https://github.com/yungyuc/nsdhw_20sp/pull/4). The last commit consist of changes of ```hw1.yml``` in my hw1 branch.

**Comment by yungyuc** [comment]
@yanagiragi Thanks a lot for the fix.  Could you test if #8 fixes the CI?

**Comment by yanagiragi** [comment]
@yungyuc It works.

I've test if the event **PR** and event **push** works in #9. The last two commit representing tests of PR event and push event, respectively. I think it should work fine for now.

There is one more thing to be mentioned: #9 still contains commits against the hand in principle. So I will close the PR if no more tests is needed and submit another PR with cleaned version of commits. Sorry for the inconvenience.

**Comment by yungyuc** [comment]
Thanks a lot @yanagiragi .  Yes please use a separate PR for submitting your homework, so that the grader @tigercosmos can distinguish it from the testing.

@tigercosmos I am leaving this issue open for the additional testing from you.  Please close it when it's done.

**Comment by tigercosmos** [comment]
sorry for the late. I am going to check it out.

**Comment by tigercosmos** [comment]
LGTM.

**Comment by yanagiragi** [comment]
Sorry for leaving comments on a closed issue.

I would like to propose a enhancement on action CI. It would be nice to slightly change ```hw1.yml``` to [this](https://github.com/yanagiragi/nsdhw_20sp/commit/9737bbd40c585ee8df6ba5410b4324dc1c07afbc). The main difference is to replace ```$GITHUB_REF``` to ```$GITHUB_REPOSITORY```.

With the change, we'll be able to test ourselves on our repository. Previous way getting ```$username``` using ```$GITHUB_REF``` are not able to achieve this. In the [previous test](https://github.com/yungyuc/nsdhw_20sp/runs/497196220?check_suite_focus=true), the action is passes since the branch name is 'yungyuc-hw1-submit-example', but in most cases the branch may not be this format (hw1, hw2, etc.). Using ```$GITHUB_REPOSITORY``` will still do the same trick but allowed students to test individually on their own forked repository. To avoid breaks after the change, I listed the possible conditions came up my mind in the below.

1. **[Behaviour changed!]** If the push is from the collaborator or the owner of base repo, e.g. @tigercosmos push a commit to yungyuc/nsdhw_20sp on branch _hw1_. The change should work well considering the output of ```$GITHUB_REPOSITORY``` in [this](https://github.com/yungyuc/nsdhw_20sp/runs/500834789?check_suite_focus=true) test.

2. **[Behaviour changed!]** If the push is from owner of forked repo to the forked repo, e.g. @yanagiragi push a commit to yanagiragi/nsdhw_20sp on branch _hw1_. The changes worked well in [here](https://github.com/yanagiragi/nsdhw_20sp/runs/501329305?check_suite_focus=true).

3. **[Behaviour changed!]** If the PR is from owner in base repo, e.g. @yungyuc send a PR from yungyuc/nsdhw_20sp branch _whatever_ to yungyuc/nsdhw_20sp on branch _hw1_. The change should work well considering the output of ```$GITHUB_REPOSITORY``` in [this](https://github.com/yungyuc/nsdhw_20sp/runs/499404877?check_suite_focus=true) test.

4. If the PR is from owner in forked repo, e.g. @yanagiragi send a PR from yanagiragi/nsdhw_20sp to yungyuc/nsdhw_20sp on branch _hw1_. The change did not break in [here](https://github.com/yungyuc/nsdhw_20sp/actions/runs/53826199).

Condition 1 and 3 has not been tested since I do not have the permission. Current solution does not support the collaborator to submit tests on it directiory (e.g. @tigercosmos wish to test hw1.yml action with files in hw1/tigercosmos on yungyuc/osd_20sp branch _hw1_ ). The collaborator might need to fork the project and test the action CI like other students.

**Comment by yungyuc** [comment]
@yanagiragi let's not comment on the closed issue.  If there's anything to be enhanced, use a new issue.

At the moment we can leave the CI as is.  We'll improve it when it is needed.
